#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 12
bspc config top_padding 30

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Rofi manage=off
