#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 12
bspc config top_padding 30

# white bright
bspc config focused_border_color '#8f8b8b'
bspc config normal_border_color '#1D1F21'
bspc config border_width 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config borderless_singleton true
bspc config single_monocle true
bspc config gapless_monocle true
