[general]
import = ["~/dotfiles/.config/alacritty/colors.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 7.1
normal = { family = "Pixel Code" }
bold = { family = "Pixel Code" }
italic = { family = "Pixel Code" }
bold_italic = { family = "Pixel Code" }

[window]
padding.x = 5
padding.y = 5
dynamic_padding = true
opacity = 1
