[colors]
[colors.primary]
background = "#1D1F21"
foreground = "#8f8b8b"
[colors.normal]
black = "#1D1F21"
red = "#a54242"
green = "#80883b"
yellow = "#9f7541"
blue = "#55748a"
magenta = "#63586e"
cyan = "#53847a"
white = "#6c8080"
[colors.bright]
black = "#40434a"
red = "#cc6666"
green = "#99a153"
yellow = "#b98c55"
blue = "#81a2be"
magenta = "#806b86"
cyan = "#609087"
white = "#8f8b8b"
